// src/types/child.ts
export type GardenStage =
  | "seed"
  | "sprout"
  | "sapling"
  | "smallTree"
  | "cocoon"
  | "butterfly"
  | "fullTree";

export type StickerTheme = "forest" | "ocean" | "space" | "flowers";

export type FavouriteAnimal =
  | "rabbit"
  | "fox"
  | "owl"
  | "butterfly"
  | "turtle"
  | "bird"
  | "cat"
  | "dog"
  | "unicorn"
  | "dinosaur";

export interface Child {
  id: string;
  name: string;
  age: number;
  favouriteColor: string;
  favouriteAnimal: FavouriteAnimal;
  stickerTheme: StickerTheme;
  culturalInterests: string[];
  gardenStage: GardenStage;
  stickerCount: number;
  badges: string[];
  createdAt: Date;
}

// Omit id (generated by Firestore) and createdAt (set server-side) for form use
export type NewChildData = Omit<Child, "id" | "createdAt">;
